### ISSUE TITLE
Stylesheet swap button disappears after first swap

### ISSUE THREAD

**Issue by xennygrimmato** [reasonml/reason-tools#14]
Noticed this after #47b3991 - when I click the stylesheet swap button, I get the OCaml doc stylesheet but the button disappears so I cannot swap back to the Reason stylesheet.

**Comment by rickyvetter** [comment]
Yeah I'm iffy on this one. I removed intentionally because I'm nervous about false positives making it hard for people to browse and would rather just throw everything away. I think that was too nervous of a decision and the buttons should stay.

**Comment by glennsl** [comment]
This was "fixed" in the reason rewrite (though I don't exactly know why). #34 also introduces a way to manually turn toggle the conversion, which also gets rid the UI.

**Comment by glennsl** [comment]
Is this still an issue?
