### ISSUE TITLE
Autoconverted ocaml docs with a certain kind of code listing isn't picked up and reformatted.

### ISSUE THREAD

**Issue by glennsl** [reasonml/reason-tools#23]
An example is the page https://caml.inria.fr/pub/docs/u3-ocaml/ocaml051.html which looks like this for me:

![2017-02-01-175549_1021x526_scrot](https://cloud.githubusercontent.com/assets/5207036/22517363/1adb95b8-e8a9-11e6-84a1-ac7cab380c6d.png)

**Comment by rickyvetter** [comment]
So it looks like these code blocks aren't getting detected properly. The markup here doesn't use <pre> or <code> so we need to figure out a way to reliably detect these blocks and then add their text to the array here: https://github.com/reasonml/reason-tools/blob/master/src/AutoConversionPrompt.js#L129. Once it's detected, I think the markup we output will be styled correctly.

**Comment by glennsl** [comment]
Right, I see I misunderstood the problem. It's not just visual, but the code blocks aren't picked up and reformatted at all. I've changed the title and am looking into it.
