### ISSUE TITLE
Odoc-generated pages aren't very readable

### ISSUE THREAD

**Issue by glennsl** [reasonml/reason-tools#27]
See: https://ocaml.janestreet.com/ocaml-core/latest/doc/core/Std/Option.mod/

___
_Edited to add:_

For comparison:

![2017-02-10-231906_252x118_scrot](https://cloud.githubusercontent.com/assets/5207036/22846392/8e66017c-efe7-11e6-8eb0-5c70cb66443e.png)

![2017-02-10-231929_274x131_scrot](https://cloud.githubusercontent.com/assets/5207036/22846391/8e6460c4-efe7-11e6-9e42-050e12c12e5d.png)

It is much easier to scan the original page for the function you are interested in.

**Comment by rickyvetter** [comment]
Are you referring to the accordion feature specifically? Or do you think everything looks bad?

**Comment by glennsl** [comment]
Apologies for my vagueness. What I mean is that it is much easier to quickly scan the page to find a specific function in the original.

**Comment by glennsl** [comment]
Compare these:

![2017-02-10-231929_274x131_scrot](https://cloud.githubusercontent.com/assets/5207036/22846391/8e6460c4-efe7-11e6-9e42-050e12c12e5d.png)
![2017-02-10-231906_252x118_scrot](https://cloud.githubusercontent.com/assets/5207036/22846392/8e66017c-efe7-11e6-8eb0-5c70cb66443e.png)

**Comment by glennsl** [comment]
This page is apparently generated by odoc. Lots more examples at https://ocaml.janestreet.com/ocaml-core/v0.9/doc/ and http://docs.mirage.io/
