### ISSUE TITLE
Feature request: a way to manually toggle the conversion of a web page

### ISSUE THREAD

**Issue by glennsl** [reasonml/reason-tools#31]
Not just for toggling off an autoconverted page, but to try conversion of one that isn't detected properly. E.g. like this page, which I think should be converted successfully if attempted:
http://caml.inria.fr/pub/docs/manual-ocaml/extn.html

**Comment by rickyvetter** [comment]
How would we do that without putting UI on every page? I'd like this feature as well, just not sure how to implement.

**Comment by glennsl** [comment]
Related to #32, in thet they both need more UI.
