### ISSUE TITLE
Build fails: cannot find reason-react

### ISSUE THREAD

**Issue by fson** [reasonml/reason-tools#52]
I'm trying to build the extension, but I'm getting an error `cannot find reason-react`:
```
> npm run build:ext

> reason-tools@0.0.17 build:ext /Users/ville/Projects/reason-tools
> eval $(dependencyEnv) && nopam && bsb -make-world


/Users/ville/Projects/reason-tools/node_modules/dependency-env/.bin/dependencyEnv.js:167
    throw err;
    ^
cannot find reason-react in /Users/ville/Projects/reason-tools,/Users/ville/Projects/reason-tools
sh: Failed: command not found

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/ville/.nvm/versions/node/v7.8.0/bin/node" "/Users/ville/.nvm/versions/node/v7.8.0/bin/npm" "run" "build:ext"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! reason-tools@0.0.17 build:ext: `eval $(dependencyEnv) && nopam && bsb -make-world`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the reason-tools@0.0.17 build:ext script 'eval $(dependencyEnv) && nopam && bsb -make-world'.
```

The problem seems to be that the `reason-react` version defined in the shrinkwrap file installs a package named `rehydrate` (the old name of `reason-react`), so `dependencyEnv` doesn't find it. I tried to upgrade to the latest `reason-react@0.1.0`, which uses the new name, but ran into other dependency issues (some inconsistencies between `package.json` and `npm-shrinkwrap.json`). A little help getting the project to build would be appreciated.

**Comment by rickyvetter** [comment]
Looking into this now and having some trouble upgrading to bs-platform 1.6.0.

**Comment by rickyvetter** [comment]
So it was easier to upgrade some libraries then try and just fix the shrinkwrap correctly. 3daa02beb41493eb93fe6983f57338faa59c9f79 should bring deps up to date and let this work on a clean install. Thanks for bringing this up! If you run into any other issues feel free to reopen and/or ping me on discord.

**Comment by fson** [comment]
Thanks @rickyvetter, it works great now.
