### ISSUE TITLE
Firefox extension link is dead

### ISSUE THREAD

**Issue by aleksandersumowski** [reasonml/reason-tools#54]
The link in the readme points to 404

**Comment by rickyvetter** [comment]
Thanks for reminding me! I've just submitted 0.0.17 to the addons site. I ran into an issue with earlier versions where the dual optimizations of jsoo and uglify made it so the code wouldn't run on FF. That appears to be cleared up now. Hopefully it will be up this week.

**Comment by rickyvetter** [comment]
Updating here since it's been well over a week. Still waiting for review. There was a one day delay on my end for not uploading the right source files and we are currently Queue Position: 480 of 617.

Based on current speed I'm estimating a review will happen in late May :(

**Comment by rickyvetter** [comment]
@aleksandersumowski it took longer than expected, but it's up now! https://addons.mozilla.org/en-US/firefox/addon/reason-tools/

**Comment by towc** [comment]
seems to be down again :/
