### ISSUE TITLE
`npm build` does not produce `extension` folder

### ISSUE THREAD

**Issue by dorafmon** [reasonml/reason-tools#76]
After I run `npm build` I got this:

```
>tree _build
_build
├── ocamlfind
│   ├── bin
│   ├── doc
│   ├── etc
│   ├── lib
│   │   ├── findlib.conf
│   │   └── ocaml -> /Users/bobfang/projects/reason-tools/node_modules/ocaml/lib/ocaml
│   ├── man
│   ├── sbin
│   └── share
└── refmt
    ├── app.byte
    ├── app.js
    ├── app.map
    ├── reasonToolsRefmt.cmi
    ├── reasonToolsRefmt.cmo
    └── reasonToolsRefmt.cmt

```
And there is no error message. Any reason you can guess? Thanks!

**Comment by dorafmon** [comment]
Seems [this line](https://github.com/reasonml/reason-tools/blob/master/package.json#L23) is only displaying webpack version for me.

**Comment by glennsl** [comment]
webpack2 has apparently changed `-v` from being a shorthand for `--verbose` to being a shorthand for `--version`. That's absolutely brilliant...

Anyway, if you change it to `--verbose` it should hopefully behave as intended. Or you could drop it, it's just there for extra debugging information.

**Comment by dorafmon** [comment]
yeah that's what I did. I will update it with my PR

**Comment by glennsl** [comment]
Cool, thanks! :)

**Comment by dorafmon** [comment]
Fixed.
