### ISSUE TITLE
Add visual indicator to show if the code is currently displayed in Ocaml or Reason syntax

### ISSUE THREAD

**Issue by kevgathuku** [reasonml/reason-tools#80]
Currently, when I click on the `Re` button provided by the extension, it displays the same, whether the current syntax is Ocaml or Reason.
![image](https://user-images.githubusercontent.com/3721994/27259303-2676a248-5418-11e7-9fbe-2c32ac0dfbd9.png)

I would suggest making the button have some visual indicator of whether the displayed code is Ocaml or Reason. 
For example, it might stay highlighted if the code is Reason, and have the current state if the code is Ocaml.

**Comment by glennsl** [comment]
It used to do that, and is supposed to, so this is definitely a bug.
