### ISSUE TITLE
Pipe operator formatting

### ISSUE THREAD

**Issue by mrkaspa** [reasonml/reason-tools#82]
It'll be better if formatting for pipe chaining will be like this

```reasonml
let prt_elems elems =>
  elems
  |> String.split on::':'
  |> List.dedup compare::String.compare
  |> List.iter f::print_endline;
```

than this

```reasonml
let prt_elems elems =>
  elems |> String.split on::':' |> List.dedup compare::String.compare |>  List.iter f::print_endline;
```

**Comment by chenglou** [comment]
Imma cc @IwanKaramazow everywhere

**Comment by rickyvetter** [comment]
Hey @mrkaspa - this file uses refmt and upstream changes to the formatter will bring the style you're recommending. Super excited for it :)

https://github.com/facebook/reason/pull/1259

**Comment by chenglou** [comment]
Fixed
