### ISSUE TITLE
Output in Firefox vs Chrome different

### ISSUE THREAD

**Issue by idkjs** [reasonml/reason-tools#88]
Firefox: [open in firefox](https://reasonml.github.io/reason-tools/popup.html#LyoqCiAqIFJlcHJlc2VudHMgYSBmdW5jdGlvbiB0YWtpbmcgZXhwcmVzcyByZXF1ZXN0IGFuZCByZXNwb25zZSB0byBvdXRwdXQgYSBwcm9taXNlIGZvciBzb21lIGdyYXBocWxPcHRpb25zCiAqLwp0eXBlIGV4cHJlc3NHcmFwaFFMT3B0aW9uc0Z1bmN0aW9uICdyb290VmFsdWUgJ2NvbnRleHQgJ3Jlc3BvbnNlID0KICBFeHByZXNzLlJlcXVlc3QudCA9PgogIEV4cHJlc3MuUmVzcG9uc2UudCA9PgogIEpzLlByb21pc2UudCAoQXBvbGxvU2VydmVyQ29yZS5ncmFwaHFsT3B0aW9ucyAncm9vdFZhbHVlICdjb250ZXh0ICdyZXNwb25zZSk7CgoKLyoqCiAqIFJlcHJlc2VudHMgYSBmdW5jdGlvbiB0YWtpbmcgZXhwcmVzcyByZXF1ZXN0IHRvIG91dHB1dCBhIHByb21pc2UgZm9yIHNvbWUgR3JhcGhpUUwgZGF0YQogKi8KdHlwZSBleHByZXNzR3JhcGhpUUxPcHRpb25zRnVuY3Rpb24gJ3ZhcmlhYmxlcyA9CiAgRXhwcmVzcy5SZXF1ZXN0LnQgPT4gSnMuUHJvbWlzZS50IChBcG9sbG9TZXJ2ZXJDb3JlLmdyYXBoaXFsRGF0YSAndmFyaWFibGVzKTsKCgovKioKICogQ2FsbHMgdGhlIGdyYXBocWxFeHByZXNzIG1pZGRsZXdhcmUgY3JlYXRpb24gd2l0aCBzdGF0aWMgb3B0aW9ucwogKi8KZXh0ZXJuYWwgZ3JhcGhxbEV4cHJlc3MgOgogIEFwb2xsb1NlcnZlckNvcmUuZ3JhcGhxbE9wdGlvbnMgJ3Jvb3RWYWx1ZSAnY29udGV4dCAncmVzcG9uc2UgPT4gRXhwcmVzcy5NaWRkbGV3YXJlLnQgPQogICJncmFwaHFsRXhwcmVzcyIgW0BAYnMubW9kdWxlICJhcG9sbG8tc2VydmVyLWV4cHJlc3MiXTsKCgovKioKICogQ2FsbHMgdGhlIGdyYXBocWxFeHByZXNzIG1pZGRsZXdhcmUgY3JlYXRpb24gd2l0aCBmdW5jdGlvbiBvcHRpb25zCiAqLwpleHRlcm5hbCBncmFwaHFsRXhwcmVzc0FzeW5jIDoKICBleHByZXNzR3JhcGhRTE9wdGlvbnNGdW5jdGlvbiAncm9vdFZhbHVlICdjb250ZXh0ICdyZXNwb25zZSA9PiBFeHByZXNzLk1pZGRsZXdhcmUudCA9CiAgImdyYXBocWxFeHByZXNzIiBbQEBicy5tb2R1bGUgImFwb2xsby1zZXJ2ZXItZXhwcmVzcyJdOwoKCi8qKgogKiBDYWxscyB0aGUgZ3JhcGhpcWxFeHByZXNzIG1pZGRsZXdhcmUgY3JlYXRpb24gd2l0aCBzdGF0aWMgb3B0aW9ucwogKi8KZXh0ZXJuYWwgZ3JhcGhpcWxFeHByZXNzIDogQXBvbGxvU2VydmVyQ29yZS5ncmFwaGlxbERhdGEgJ3ZhcmlhYmxlcyA9PiBFeHByZXNzLk1pZGRsZXdhcmUudCA9CiAgImdyYXBoaXFsRXhwcmVzcyIgW0BAYnMubW9kdWxlICJhcG9sbG8tc2VydmVyLWV4cHJlc3MiXTsKCgovKioKICogQ2FsbHMgdGhlIGdyYXBoaXFsRXhwcmVzcyBtaWRkbGV3YXJlIGNyZWF0aW9uIHdpdGggZnVuY3Rpb24gb3B0aW9ucwogKi8KZXh0ZXJuYWwgZ3JhcGhpcWxFeHByZXNzQXN5bmMgOiBleHByZXNzR3JhcGhpUUxPcHRpb25zRnVuY3Rpb24gJ3ZhcmlhYmxlcyA9PiBFeHByZXNzLk1pZGRsZXdhcmUudCA9CiAgImdyYXBoaXFsRXhwcmVzcyIgW0BAYnMubW9kdWxlICJhcG9sbG8tc2VydmVyLWV4cHJlc3MiXTsKCgovKioKICogVXNhYmlsaXR5IHdyYXBwZXIgYXJvdW5kIHRoZSBzdGF0aWMgZ3JhcGhxbEV4cHJlc3MgZnVuY3Rpb24KICovCmxldCBjcmVhdGVHcmFwaFFMRXhwcmVzc01pZGRsZXdhcmUKICAgIDo6Zm9ybWF0RXJyb3I9PwogICAgOjpyb290VmFsdWU9PwogICAgOjpjb250ZXh0PT8KICAgIDo6bG9nRnVuY3Rpb249PwogICAgOjpmb3JtYXRQYXJhbXM9PwogICAgOjp2YWxpZGF0aW9uUnVsZXM9PwogICAgOjpmb3JtYXRSZXNwb25zZT0/CiAgICA6OmZpZWxkUmVzb2x2ZXI9PwogICAgOjpkZWJ1Zz0/CiAgICBzY2hlbWEgPT4KICBncmFwaHFsRXhwcmVzcyB7CiAgICAic2NoZW1hIjogc2NoZW1hLAogICAgImZvcm1hdEVycm9yIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgZm9ybWF0RXJyb3IsCiAgICAicm9vdFZhbHVlIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgcm9vdFZhbHVlLAogICAgImNvbnRleHQiOiBKcy5OdWxsX3VuZGVmaW5lZC5mcm9tX29wdCBjb250ZXh0LAogICAgImxvZ0Z1bmN0aW9uIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgbG9nRnVuY3Rpb24sCiAgICAiZm9ybWF0UGFyYW1zIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgZm9ybWF0UGFyYW1zLAogICAgInZhbGlkYXRpb25SdWxlcyI6IEpzLk51bGxfdW5kZWZpbmVkLmZyb21fb3B0IHZhbGlkYXRpb25SdWxlcywKICAgICJmb3JtYXRSZXNwb25zZSI6IEpzLk51bGxfdW5kZWZpbmVkLmZyb21fb3B0IGZvcm1hdFJlc3BvbnNlLAogICAgImZpZWxkUmVzb2x2ZXIiOiBKcy5OdWxsX3VuZGVmaW5lZC5mcm9tX29wdCBmaWVsZFJlc29sdmVyLAogICAgImRlYnVnIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgZGVidWcKICB9OwoKCi8qKgogKiBVc2FiaWxpdHkgd3JhcHBlciBhcm91bmQgdGhlIHN0YXRpYyBncmFwaGlxbEV4cHJlc3MgZnVuY3Rpb24KICovCmxldCBjcmVhdGVHcmFwaGlRTEV4cHJlc3NNaWRkbGV3YXJlCiAgICA6OnF1ZXJ5PT8KICAgIDo6dmFyaWFibGVzPT8KICAgIDo6b3BlcmF0aW9uTmFtZT0/CiAgICA6OnJlc3VsdD0/CiAgICBlbmRwb2ludFVSTCA9PgogIGdyYXBoaXFsRXhwcmVzcyB7CiAgICAiZW5kcG9pbnRVUkwiOiBlbmRwb2ludFVSTCwKICAgICJxdWVyeSI6IEpzLk51bGxfdW5kZWZpbmVkLmZyb21fb3B0IHF1ZXJ5LAogICAgInZhcmlhYmxlcyI6IEpzLk51bGxfdW5kZWZpbmVkLmZyb21fb3B0IHZhcmlhYmxlcywKICAgICJvcGVyYXRpb25OYW1lIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgb3BlcmF0aW9uTmFtZSwKICAgICJyZXN1bHQiOiBKcy5OdWxsX3VuZGVmaW5lZC5mcm9tX29wdCByZXN1bHQKICB9Owo=)

Chrome: [open in chrome](https://reasonml.github.io/reason-tools/popup.html#LyoqCiAqIFJlcHJlc2VudHMgYSBmdW5jdGlvbiB0YWtpbmcgZXhwcmVzcyByZXF1ZXN0IGFuZCByZXNwb25zZSB0byBvdXRwdXQgYSBwcm9taXNlIGZvciBzb21lIGdyYXBocWxPcHRpb25zCiAqLwp0eXBlIGV4cHJlc3NHcmFwaFFMT3B0aW9uc0Z1bmN0aW9uICdyb290VmFsdWUgJ2NvbnRleHQgJ3Jlc3BvbnNlID0KICBFeHByZXNzLlJlcXVlc3QudCA9PgogIEV4cHJlc3MuUmVzcG9uc2UudCA9PgogIEpzLlByb21pc2UudCAoQXBvbGxvU2VydmVyQ29yZS5ncmFwaHFsT3B0aW9ucyAncm9vdFZhbHVlICdjb250ZXh0ICdyZXNwb25zZSk7CgoKLyoqCiAqIFJlcHJlc2VudHMgYSBmdW5jdGlvbiB0YWtpbmcgZXhwcmVzcyByZXF1ZXN0IHRvIG91dHB1dCBhIHByb21pc2UgZm9yIHNvbWUgR3JhcGhpUUwgZGF0YQogKi8KdHlwZSBleHByZXNzR3JhcGhpUUxPcHRpb25zRnVuY3Rpb24gJ3ZhcmlhYmxlcyA9CiAgRXhwcmVzcy5SZXF1ZXN0LnQgPT4gSnMuUHJvbWlzZS50IChBcG9sbG9TZXJ2ZXJDb3JlLmdyYXBoaXFsRGF0YSAndmFyaWFibGVzKTsKCgovKioKICogQ2FsbHMgdGhlIGdyYXBocWxFeHByZXNzIG1pZGRsZXdhcmUgY3JlYXRpb24gd2l0aCBzdGF0aWMgb3B0aW9ucwogKi8KZXh0ZXJuYWwgZ3JhcGhxbEV4cHJlc3MgOgogIEFwb2xsb1NlcnZlckNvcmUuZ3JhcGhxbE9wdGlvbnMgJ3Jvb3RWYWx1ZSAnY29udGV4dCAncmVzcG9uc2UgPT4gRXhwcmVzcy5NaWRkbGV3YXJlLnQgPQogICJncmFwaHFsRXhwcmVzcyIgW0BAYnMubW9kdWxlICJhcG9sbG8tc2VydmVyLWV4cHJlc3MiXTsKCgovKioKICogQ2FsbHMgdGhlIGdyYXBocWxFeHByZXNzIG1pZGRsZXdhcmUgY3JlYXRpb24gd2l0aCBmdW5jdGlvbiBvcHRpb25zCiAqLwpleHRlcm5hbCBncmFwaHFsRXhwcmVzc0FzeW5jIDoKICBleHByZXNzR3JhcGhRTE9wdGlvbnNGdW5jdGlvbiAncm9vdFZhbHVlICdjb250ZXh0ICdyZXNwb25zZSA9PiBFeHByZXNzLk1pZGRsZXdhcmUudCA9CiAgImdyYXBocWxFeHByZXNzIiBbQEBicy5tb2R1bGUgImFwb2xsby1zZXJ2ZXItZXhwcmVzcyJdOwoKCi8qKgogKiBDYWxscyB0aGUgZ3JhcGhpcWxFeHByZXNzIG1pZGRsZXdhcmUgY3JlYXRpb24gd2l0aCBzdGF0aWMgb3B0aW9ucwogKi8KZXh0ZXJuYWwgZ3JhcGhpcWxFeHByZXNzIDogQXBvbGxvU2VydmVyQ29yZS5ncmFwaGlxbERhdGEgJ3ZhcmlhYmxlcyA9PiBFeHByZXNzLk1pZGRsZXdhcmUudCA9CiAgImdyYXBoaXFsRXhwcmVzcyIgW0BAYnMubW9kdWxlICJhcG9sbG8tc2VydmVyLWV4cHJlc3MiXTsKCgovKioKICogQ2FsbHMgdGhlIGdyYXBoaXFsRXhwcmVzcyBtaWRkbGV3YXJlIGNyZWF0aW9uIHdpdGggZnVuY3Rpb24gb3B0aW9ucwogKi8KZXh0ZXJuYWwgZ3JhcGhpcWxFeHByZXNzQXN5bmMgOiBleHByZXNzR3JhcGhpUUxPcHRpb25zRnVuY3Rpb24gJ3ZhcmlhYmxlcyA9PiBFeHByZXNzLk1pZGRsZXdhcmUudCA9CiAgImdyYXBoaXFsRXhwcmVzcyIgW0BAYnMubW9kdWxlICJhcG9sbG8tc2VydmVyLWV4cHJlc3MiXTsKCgovKioKICogVXNhYmlsaXR5IHdyYXBwZXIgYXJvdW5kIHRoZSBzdGF0aWMgZ3JhcGhxbEV4cHJlc3MgZnVuY3Rpb24KICovCmxldCBjcmVhdGVHcmFwaFFMRXhwcmVzc01pZGRsZXdhcmUKICAgIDo6Zm9ybWF0RXJyb3I9PwogICAgOjpyb290VmFsdWU9PwogICAgOjpjb250ZXh0PT8KICAgIDo6bG9nRnVuY3Rpb249PwogICAgOjpmb3JtYXRQYXJhbXM9PwogICAgOjp2YWxpZGF0aW9uUnVsZXM9PwogICAgOjpmb3JtYXRSZXNwb25zZT0/CiAgICA6OmZpZWxkUmVzb2x2ZXI9PwogICAgOjpkZWJ1Zz0/CiAgICBzY2hlbWEgPT4KICBncmFwaHFsRXhwcmVzcyB7CiAgICAic2NoZW1hIjogc2NoZW1hLAogICAgImZvcm1hdEVycm9yIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgZm9ybWF0RXJyb3IsCiAgICAicm9vdFZhbHVlIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgcm9vdFZhbHVlLAogICAgImNvbnRleHQiOiBKcy5OdWxsX3VuZGVmaW5lZC5mcm9tX29wdCBjb250ZXh0LAogICAgImxvZ0Z1bmN0aW9uIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgbG9nRnVuY3Rpb24sCiAgICAiZm9ybWF0UGFyYW1zIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgZm9ybWF0UGFyYW1zLAogICAgInZhbGlkYXRpb25SdWxlcyI6IEpzLk51bGxfdW5kZWZpbmVkLmZyb21fb3B0IHZhbGlkYXRpb25SdWxlcywKICAgICJmb3JtYXRSZXNwb25zZSI6IEpzLk51bGxfdW5kZWZpbmVkLmZyb21fb3B0IGZvcm1hdFJlc3BvbnNlLAogICAgImZpZWxkUmVzb2x2ZXIiOiBKcy5OdWxsX3VuZGVmaW5lZC5mcm9tX29wdCBmaWVsZFJlc29sdmVyLAogICAgImRlYnVnIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgZGVidWcKICB9OwoKCi8qKgogKiBVc2FiaWxpdHkgd3JhcHBlciBhcm91bmQgdGhlIHN0YXRpYyBncmFwaGlxbEV4cHJlc3MgZnVuY3Rpb24KICovCmxldCBjcmVhdGVHcmFwaGlRTEV4cHJlc3NNaWRkbGV3YXJlCiAgICA6OnF1ZXJ5PT8KICAgIDo6dmFyaWFibGVzPT8KICAgIDo6b3BlcmF0aW9uTmFtZT0/CiAgICA6OnJlc3VsdD0/CiAgICBlbmRwb2ludFVSTCA9PgogIGdyYXBoaXFsRXhwcmVzcyB7CiAgICAiZW5kcG9pbnRVUkwiOiBlbmRwb2ludFVSTCwKICAgICJxdWVyeSI6IEpzLk51bGxfdW5kZWZpbmVkLmZyb21fb3B0IHF1ZXJ5LAogICAgInZhcmlhYmxlcyI6IEpzLk51bGxfdW5kZWZpbmVkLmZyb21fb3B0IHZhcmlhYmxlcywKICAgICJvcGVyYXRpb25OYW1lIjogSnMuTnVsbF91bmRlZmluZWQuZnJvbV9vcHQgb3BlcmF0aW9uTmFtZSwKICAgICJyZXN1bHQiOiBKcy5OdWxsX3VuZGVmaW5lZC5mcm9tX29wdCByZXN1bHQKICB9Owo=)

**Comment by rickyvetter** [comment]
Fixed in 0.3.1 release on FF! Thanks for posting.
